### Scalars

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
x = 25
x

25

In [3]:
x_pt = torch.tensor(25)
x_pt

tensor(25)

In [4]:
x_pt.shape

torch.Size([])

In [5]:
x_tf = tf.Variable(25, dtype=tf.int16)

In [6]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [7]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [8]:
tf_sum = tf.add(x_tf, y_tf)

In [9]:
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [10]:
tf_sum.numpy()

28

In [11]:
tf_float = tf.Variable(25, dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

### Vectors

In [12]:
x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

In [13]:
len(x)

3

In [14]:
x.shape

(3,)

In [15]:
x.T

array([25,  2,  5])

In [16]:
x.T.shape

(3,)

In [17]:
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [18]:
y.shape

(1, 3)

In [19]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [20]:
y_t.shape

(3, 1)

In [21]:
y_t.T.shape

(1, 3)

In [22]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [23]:
x_pt = torch.tensor([8, 6, 19, 0])
x_pt

tensor([ 8,  6, 19,  0])

In [24]:
np.linalg.norm(x_pt) #L2-Norm, дляна вектора

21.470910553583888

In [25]:
np.dot(x_pt,x_pt)

461

In [26]:
np.linalg.norm(x_pt) ** 2 # Squared L2-Norm

461.0

### Matrix Tensors

In [27]:
X = np.array([[2,2,3,4],[3,5,0,0],[5,1,1,8]])
X

array([[2, 2, 3, 4],
       [3, 5, 0, 0],
       [5, 1, 1, 8]])

In [28]:
X.size

12

In [29]:
X.shape

(3, 4)

In [30]:
X.T

array([[2, 3, 5],
       [2, 5, 1],
       [3, 0, 1],
       [4, 0, 8]])

In [31]:
X_gram = np.dot(X, X.T)

In [32]:
X_gram

array([[33, 16, 47],
       [16, 34, 20],
       [47, 20, 91]])

In [33]:
np.linalg.matrix_rank(X)

3

In [34]:
np.linalg.matrix_rank(X_gram)

3

In [35]:
np.linalg.inv(X_gram)

array([[ 0.13090379, -0.02507289, -0.06209913],
       [-0.02507289,  0.03858115,  0.00447036],
       [-0.06209913,  0.00447036,  0.04207969]])

In [36]:
np.dot(X_gram, np.linalg.inv(X_gram))

array([[ 1.00000000e+00, -1.82145965e-17, -4.16333634e-17],
       [-5.55111512e-17,  1.00000000e+00,  5.55111512e-17],
       [-3.19189120e-16, -4.94396191e-17,  1.00000000e+00]])

In [37]:
X_pt = torch.tensor([[2,2,3,4],[3,5,0,0],[5,1,1,8]])
X_pt

tensor([[2, 2, 3, 4],
        [3, 5, 0, 0],
        [5, 1, 1, 8]])

In [38]:
X_tf = tf.Variable([[2,2,3,4],[3,5,0,0],[5,1,1,8]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[2, 2, 3, 4],
       [3, 5, 0, 0],
       [5, 1, 1, 8]], dtype=int32)>

In [39]:
np.zeros([3,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [40]:
X

array([[2, 2, 3, 4],
       [3, 5, 0, 0],
       [5, 1, 1, 8]])

In [41]:
C = X * 3 @ X.T 
C

array([[ 99,  48, 141],
       [ 48, 102,  60],
       [141,  60, 273]])

In [42]:
C.shape

(3, 3)

In [43]:
D = np.array([[14,54,-8],[90,90,60],[-19,-4,0]])
D

array([[ 14,  54,  -8],
       [ 90,  90,  60],
       [-19,  -4,   0]])

In [44]:
F = D + C
F

array([[113, 102, 133],
       [138, 192, 120],
       [122,  56, 273]])

In [45]:
np.linalg.matrix_rank(F)

3

In [46]:
J = np.array([[2,13,3],[6,6,9],[88,0,0]])
J

array([[ 2, 13,  3],
       [ 6,  6,  9],
       [88,  0,  0]])

In [47]:
np.linalg.matrix_rank(J)

3

In [48]:
# elementwise multiplication: Hadamard product
F * J

array([[  226,  1326,   399],
       [  828,  1152,  1080],
       [10736,     0,     0]])

In [49]:
F.sum()

1249

In [50]:
F.sum(axis=0), F.sum(axis=1)

(array([373, 350, 526]), array([348, 450, 451]))

In [51]:
F.min()

56

In [52]:
a = F.min(1)
b = F.max(0)
a, b

(array([102, 120,  56]), array([138, 192, 273]))

In [53]:
c = np.dot(a.T,b)

In [54]:
a @ b

52404